import { getPricePrecision } from '../utils/volatilityDetector';
import type { AnchoredPriceResult } from './priceAnchor';
import type { VisionAnalysisResult } from './visionAnalysis';

export interface TradeSignalResult {
  bias: 'bullish' | 'bearish' | 'neutral';
  confidence: number;
  currentPrice: number;
  entry: number | null;
  stopLoss: number | null;
  takeProfits: number[];
  riskReward: string | null;
  entryType: VisionAnalysisResult['entryType'];
  recommendation: VisionAnalysisResult['recommendation'];
  reasoning: string;
  trendStrength: VisionAnalysisResult['trendStrength'];
  structure: VisionAnalysisResult['structure'];
  structureSummary: string;
  liquidityContext: string;
  clarity: VisionAnalysisResult['clarity'];
  range: number;
  buffer: number;
  priceSource: AnchoredPriceResult['priceSource'];
  provider: 'gemini-vision+anchor';
}

const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));

const formatPrice = (value: number, pair: string) => value.toFixed(getPricePrecision(pair));

export function buildTradeSignal(pair: string, vision: VisionAnalysisResult, anchor: AnchoredPriceResult): TradeSignalResult {
  let confidence = 30;

  if (vision.bias !== 'neutral') confidence += 15;
  if (vision.trendStrength === 'strong') confidence += 25;
  if (vision.trendStrength === 'moderate') confidence += 15;
  if (vision.clarity === 'clear') confidence += 20;
  if (vision.clarity === 'mixed') confidence += 8;
  if (vision.entryType === 'breakout') confidence += 5;
  if (vision.entryType === 'pullback') confidence += 8;
  if (vision.liquidityContext.includes('above') || vision.liquidityContext.includes('below')) confidence += 5;
  if (anchor.shouldWait) confidence -= 22;

  confidence = clamp(confidence, 15, 95);

  if (anchor.shouldWait) {
    confidence = Math.min(confidence, 45);
  }

  const reasoning = anchor.shouldWait
    ? `${vision.structureSummary} Gemini marked the chart as ${vision.clarity}, so the engine keeps the recommendation on wait. No exact prices were generated by AI. Trade levels are withheld until structure becomes cleaner around the supplied current price of ${formatPrice(anchor.currentPrice, pair)}.`
    : `${vision.structureSummary} Bias is ${vision.bias} with ${vision.trendStrength} trend pressure and ${vision.entryType} conditions. Liquidity is positioned ${vision.liquidityContext}. Entry, stop loss, and targets are anchored mechanically to the supplied current price of ${formatPrice(anchor.currentPrice, pair)} using a ${formatPrice(anchor.range, pair)} working range and ${formatPrice(anchor.buffer, pair)} execution buffer, which avoids image-based fake precision.`;

  return {
    bias: vision.bias,
    confidence,
    currentPrice: anchor.currentPrice,
    entry: anchor.entry,
    stopLoss: anchor.stopLoss,
    takeProfits: anchor.takeProfits,
    riskReward: anchor.riskReward,
    entryType: vision.entryType,
    recommendation: anchor.shouldWait ? 'wait' : vision.recommendation,
    reasoning,
    trendStrength: vision.trendStrength,
    structure: vision.structure,
    structureSummary: vision.structureSummary,
    liquidityContext: vision.liquidityContext,
    clarity: vision.clarity,
    range: anchor.range,
    buffer: anchor.buffer,
    priceSource: anchor.priceSource,
    provider: 'gemini-vision+anchor',
  };
}